// This file was auto-generated by ML.NET Model Builder. 

using System;
using LanguageDetectionMLML.Model;
using static Tensorflow.Binding;

namespace LanguageDetectionMLML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Content = "'const arr = [\"This\", \"Little\", \"Piggy\"]; const first = arr.pop(); console.log(first);')"
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Language with predicted Language from sample data...\n\n");
            Console.WriteLine($"Content: {sampleData.Content}");
            Console.WriteLine($"\n\nPredicted Language value {predictionResult.Prediction} \nPredicted Language scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
